# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
      - skip-rn
      - skip-release-note
      - no-rn
      - no-changelog
      - new-release
  categories:
    - title: Exciting New Features 🎉
      labels:
        - feature
    - title: Bugs
      labels:
        - hotfix
        - fix
        - bugs
        - bug
    - title: Other Changes
      labels:
        - "*"
